name: YT-DLP Download
on:
  push:
    branches: [ main ]
    paths:
      - 'playlist.txt'

permissions:
  contents: read
  packages: read
  actions: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 安装 yt-dlp + ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install yt-dlp

      - name: 开始批量下载视频
        run: |
          mkdir -p output
          yt-dlp -a playlist.txt -o "output/%(title)s.%(ext)s" -f "bv*+ba/b" --merge-output-format mp4

      - name: 上传打包文件到Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: youtube下载视频
          path: output/

